# Generated by Django 3.2.12 on 2022-11-20 22:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccionEstrategica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Accion Estrategica')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Description de la accion estrategica')),
            ],
            options={
                'db_table': 'TB_AccionEstrategica',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='AreaPriorizada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Area')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Description de la area')),
            ],
            options={
                'db_table': 'TB_Area',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Indicador')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Description del indicador')),
                ('unidad_medida', models.CharField(max_length=200, verbose_name='U/M')),
            ],
            options={
                'db_table': 'TB_Indicador',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Organismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Organismo')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Description de organismo')),
            ],
            options={
                'db_table': 'TB_Organismo',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Tarea')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Description de la tarea')),
            ],
            options={
                'db_table': 'TB_Tarea',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Plan')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Descripción del plan')),
                ('acciones_estrategica_id', models.ManyToManyField(to='sigma_metas.AccionEstrategica', verbose_name='Acción estrategica')),
                ('tareas_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sigma_metas.tarea', verbose_name='Tareas')),
            ],
            options={
                'db_table': 'TB_PLan',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Meta')),
                ('descripcion', models.TextField(max_length=500, verbose_name='Description de la meta')),
                ('acciones_estrategica_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sigma_metas.accionestrategica', verbose_name='Acciones')),
                ('indicador_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sigma_metas.indicador', verbose_name='Indicadores')),
                ('organismo_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sigma_metas.organismo', verbose_name='Meta')),
            ],
            options={
                'db_table': 'TB_Meta',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre de la Accion')),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0, message='El importe debe ser positivo')], verbose_name='Presupuesto')),
                ('financiamiento', models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0, message='El importe debe ser positivo')], verbose_name='Financiamiento')),
                ('fuente_financimiento', models.CharField(max_length=200, verbose_name='Fuente de financiamiento')),
                ('estado', models.CharField(choices=[('realizado', 'Realizado'), ('aplazado', 'Aplazado'), ('pendiente', 'Pendiente')], max_length=15, verbose_name='Estado de la accion')),
                ('observacion', models.CharField(max_length=500, verbose_name='Observaciones')),
                ('area_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma_metas.areapriorizada', verbose_name='Areas Priorizadas')),
                ('organismo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma_metas.organismo', verbose_name='Organismo')),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sigma_metas.tarea', verbose_name='Organismo')),
            ],
            options={
                'db_table': 'TB_Accion',
                'ordering': ['-id'],
                'permissions': (),
                'default_permissions': [],
            },
        ),
    ]
